import type { Metadata } from "next";
import Script from "next/script";
import localFont from "next/font/local";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import UserProvider from "@/components/Providers/UserProvider";
import QueryClientWrapper from "@/components/Providers/QueryClientWrapper";
import { TWARoot } from "@/components/Root/TWARoot";
import { getSession } from "./init-data/auth/session";
import "@/css/globals.scss";
import "@/css/main.scss";

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  console.log('layout.tsx');
  const session = await getSession();
  console.log('layout.tsx session:'); console.log(session);

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Script src="https://telegram.org/js/telegram-web-app.js" strategy="afterInteractive"/>

        <QueryClientWrapper>
          <UserProvider session={session}>
            <TWARoot>
              <div className="layout-grid min-h-screen font-[family-name:var(--font-geist-sans)]">
                <Header />
                
                <main className="layout-content">
                  {children}
                </main>

                <Footer />
              </div>
            </TWARoot>
          </UserProvider>
        </QueryClientWrapper>
      </body>
    </html>
  );
}
