import type { Metadata } from "next";
import Script from "next/script";
import localFont from "next/font/local";
import Header from "@/components/header/header";
import Footer from "@/components/footer/footer";
import UserProvider from "@/components/providers/user-provider";
import TonConnectWrapper from "@/components/providers/ton-connect-wrapper";
import QueryClientWrapper from "@/components/providers/query-client-wrapper";
import "@/css/globals.scss";
import "@/css/main.scss";



const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { TWARoot } from "@/components/Root/TWARoot";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Script src="https://telegram.org/js/telegram-web-app.js" strategy="afterInteractive"/>

        <QueryClientWrapper>
          <TonConnectWrapper>
            <TWARoot>
              <UserProvider>
                <div className="layout-grid min-h-screen font-[family-name:var(--font-geist-sans)]">
                  <Header />
                  
                  <main className="layout-content">
                    {children}
                  </main>

                  <Footer />
                </div>
              </UserProvider>
            </TWARoot>
          </TonConnectWrapper>
        </QueryClientWrapper>
      </body>
    </html>
  );
}
